local MarketplaceService = game:GetService("MarketplaceService")
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")
local HttpService = game:GetService("HttpService")
local RunService = game:GetService("RunService")
local CoreGui = game:GetService("CoreGui")
local Players = game:GetService("Players")
local Player = Players.LocalPlayer
local PlayerMouse = Player:GetMouse()

local redzlib = {
	Themes = {
		Darker = {
			["Color Hub 1"] = ColorSequence.new({
				ColorSequenceKeypoint.new(0.00, Color3.fromRGB(25, 25, 25)),
				ColorSequenceKeypoint.new(0.50, Color3.fromRGB(32.5, 32.5, 32.5)),
				ColorSequenceKeypoint.new(1.00, Color3.fromRGB(25, 25, 25))
			}),
			["Color Hub 2"] = Color3.fromRGB(30, 30, 30),
			["Color Stroke"] = Color3.fromRGB(40, 40, 40),
			["Color Theme"] = Color3.fromRGB(88, 101, 242),
			["Color Text"] = Color3.fromRGB(243, 243, 243),
			["Color Dark Text"] = Color3.fromRGB(180, 180, 180)
		},
		Dark = {
			["Color Hub 1"] = ColorSequence.new({
				ColorSequenceKeypoint.new(0.00, Color3.fromRGB(40, 40, 40)),
				ColorSequenceKeypoint.new(0.50, Color3.fromRGB(47.5, 47.5, 47.5)),
				ColorSequenceKeypoint.new(1.00, Color3.fromRGB(40, 40, 40))
			}),
			["Color Hub 2"] = Color3.fromRGB(45, 45, 45),
			["Color Stroke"] = Color3.fromRGB(65, 65, 65),
			["Color Theme"] = Color3.fromRGB(65, 150, 255),
			["Color Text"] = Color3.fromRGB(245, 245, 245),
			["Color Dark Text"] = Color3.fromRGB(190, 190, 190)
		},
		Purple = {
			["Color Hub 1"] = ColorSequence.new({
				ColorSequenceKeypoint.new(0.00, Color3.fromRGB(27.5, 25, 30)),
				ColorSequenceKeypoint.new(0.50, Color3.fromRGB(32.5, 32.5, 32.5)),
				ColorSequenceKeypoint.new(1.00, Color3.fromRGB(27.5, 25, 30))
			}),
			["Color Hub 2"] = Color3.fromRGB(30, 30, 30),
			["Color Stroke"] = Color3.fromRGB(40, 40, 40),
			["Color Theme"] = Color3.fromRGB(150, 0, 255),
			["Color Text"] = Color3.fromRGB(240, 240, 240),
			["Color Dark Text"] = Color3.fromRGB(180, 180, 180)
		}
	},
	Info = {
		Version = "1.1.0"
	},
	Save = {
		UISize = {550, 380},
		TabSize = 160,
		Theme = "Darker"
	},
	Settings = {},
	Connection = {},
	Instances = {},
	Elements = {},
	Options = {},
	Flags = {},
	Tabs = {},
	Icons = (function()
	  -- This file was @generated by Tarmac. It is not intended for manual editing.
		return {
			["accessibility"] = "rbxassetid://10709751939",
			["activity"] = "rbxassetid://10709752035",
			["airvent"] = "rbxassetid://10709752131",
			["airplay"] = "rbxassetid://10709752254",
			["alarmcheck"] = "rbxassetid://10709752405",
			["alarmclock"] = "rbxassetid://10709752630",
			["alarmclockoff"] = "rbxassetid://10709752508",
			["alarmminus"] = "rbxassetid://10709752732",
			["alarmplus"] = "rbxassetid://10709752825",
			["album"] = "rbxassetid://10709752906",
			["alertcircle"] = "rbxassetid://10709752996",
			["alertoctagon"] = "rbxassetid://10709753064",
			["alerttriangle"] = "rbxassetid://10709753149",
			["aligncenter"] = "rbxassetid://10709753570",
			["aligncenterhorizontal"] = "rbxassetid://10709753272",
			["aligncentervertical"] = "rbxassetid://10709753421",
			["alignendhorizontal"] = "rbxassetid://10709753692",
			["alignendvertical"] = "rbxassetid://10709753808",
			["alignhorizontaldistributecenter"] = "rbxassetid://10747779791",
			["alignhorizontaldistributeend"] = "rbxassetid://10747784534",
			["alignhorizontaldistributestart"] = "rbxassetid://10709754118",
			["alignhorizontaljustifycenter"] = "rbxassetid://10709754204",
			["alignhorizontaljustifyend"] = "rbxassetid://10709754317",
			["alignhorizontaljustifystart"] = "rbxassetid://10709754436",
			["alignhorizontalspacearound"] = "rbxassetid://10709754590",
			["alignhorizontalspacebetween"] = "rbxassetid://10709754749",
			["alignjustify"] = "rbxassetid://10709759610",
			["alignleft"] = "rbxassetid://10709759764",
			["alignright"] = "rbxassetid://10709759895",
			["alignstarthorizontal"] = "rbxassetid://10709760051",
			["alignstartvertical"] = "rbxassetid://10709760244",
			["alignverticaldistributecenter"] = "rbxassetid://10709760351",
			["alignverticaldistributeend"] = "rbxassetid://10709760434",
			["alignverticaldistributestart"] = "rbxassetid://10709760612",
			["alignverticaljustifycenter"] = "rbxassetid://10709760814",
			["alignverticaljustifyend"] = "rbxassetid://10709761003",
			["alignverticaljustifystart"] = "rbxassetid://10709761176",
			["alignverticalspacearound"] = "rbxassetid://10709761324",
			["alignverticalspacebetween"] = "rbxassetid://10709761434",
			["anchor"] = "rbxassetid://10709761530",
			["angry"] = "rbxassetid://10709761629",
			["annoyed"] = "rbxassetid://10709761722",
			["aperture"] = "rbxassetid://10709761813",
			["apple"] = "rbxassetid://10709761889",
			["archive"] = "rbxassetid://10709762233",
			["archiverestore"] = "rbxassetid://10709762058",
			["armchair"] = "rbxassetid://10709762327",
			["arrowbigdown"] = "rbxassetid://10747796644",
			["arrowbigleft"] = "rbxassetid://10709762574",
			["arrowbigright"] = "rbxassetid://10709762727",
			["arrowbigup"] = "rbxassetid://10709762879",
			["arrowdown"] = "rbxassetid://10709767827",
			["arrowdowncircle"] = "rbxassetid://10709763034",
			["arrowdownleft"] = "rbxassetid://10709767656",
			["arrowdownright"] = "rbxassetid://10709767750",
			["arrowleft"] = "rbxassetid://10709768114",
			["arrowleftcircle"] = "rbxassetid://10709767936",
			["arrowleftright"] = "rbxassetid://10709768019",
			["arrowright"] = "rbxassetid://10709768347",
			["arrowrightcircle"] = "rbxassetid://10709768226",
			["arrowup"] = "rbxassetid://10709768939",
			["arrowupcircle"] = "rbxassetid://10709768432",
			["arrowupdown"] = "rbxassetid://10709768538",
			["arrowupleft"] = "rbxassetid://10709768661",
			["arrowupright"] = "rbxassetid://10709768787",
			["asterisk"] = "rbxassetid://10709769095",
			["atsign"] = "rbxassetid://10709769286",
			["award"] = "rbxassetid://10709769406",
			["axe"] = "rbxassetid://10709769508",
			["axis3d"] = "rbxassetid://10709769598",
			["baby"] = "rbxassetid://10709769732",
			["backpack"] = "rbxassetid://10709769841",
			["baggageclaim"] = "rbxassetid://10709769935",
			["banana"] = "rbxassetid://10709770005",
			["banknote"] = "rbxassetid://10709770178",
			["barchart"] = "rbxassetid://10709773755",
			["barchart2"] = "rbxassetid://10709770317",
			["barchart3"] = "rbxassetid://10709770431",
			["barchart4"] = "rbxassetid://10709770560",
			["barcharthorizontal"] = "rbxassetid://10709773669",
			["barcode"] = "rbxassetid://10747360675",
			["baseline"] = "rbxassetid://10709773863",
			["bath"] = "rbxassetid://10709773963",
			["battery"] = "rbxassetid://10709774640",
			["batterycharging"] = "rbxassetid://10709774068",
			["batteryfull"] = "rbxassetid://10709774206",
			["batterylow"] = "rbxassetid://10709774370",
			["batterymedium"] = "rbxassetid://10709774513",
			["beaker"] = "rbxassetid://10709774756",
			["bed"] = "rbxassetid://10709775036",
			["beddouble"] = "rbxassetid://10709774864",
			["bedsingle"] = "rbxassetid://10709774968",
			["beer"] = "rbxassetid://10709775167",
			["bell"] = "rbxassetid://10709775704",
			["bellminus"] = "rbxassetid://10709775241",
			["belloff"] = "rbxassetid://10709775320",
			["bellplus"] = "rbxassetid://10709775448",
			["bellring"] = "rbxassetid://10709775560",
			["bike"] = "rbxassetid://10709775894",
			["binary"] = "rbxassetid://10709776050",
			["bitcoin"] = "rbxassetid://10709776126",
			["bluetooth"] = "rbxassetid://10709776655",
			["bluetoothconnected"] = "rbxassetid://10709776240",
			["bluetoothoff"] = "rbxassetid://10709776344",
			["bluetoothsearching"] = "rbxassetid://10709776501",
			["bold"] = "rbxassetid://10747813908",
			["bomb"] = "rbxassetid://10709781460",
			["bone"] = "rbxassetid://10709781605",
			["book"] = "rbxassetid://10709781824",
			["bookopen"] = "rbxassetid://10709781717",
			["bookmark"] = "rbxassetid://10709782154",
			["bookmarkminus"] = "rbxassetid://10709781919",
			["bookmarkplus"] = "rbxassetid://10709782044",
			["bot"] = "rbxassetid://10709782230",
			["box"] = "rbxassetid://10709782497",
			["boxselect"] = "rbxassetid://10709782342",
			["boxes"] = "rbxassetid://10709782582",
			["briefcase"] = "rbxassetid://10709782662",
			["brush"] = "rbxassetid://10709782758",
			["bug"] = "rbxassetid://10709782845",
			["building"] = "rbxassetid://10709783051",
			["building2"] = "rbxassetid://10709782939",
			["bus"] = "rbxassetid://10709783137",
			["cake"] = "rbxassetid://10709783217",
			["calculator"] = "rbxassetid://10709783311",
			["calendar"] = "rbxassetid://10709789505",
			["calendarcheck"] = "rbxassetid://10709783474",
			["calendarcheck2"] = "rbxassetid://10709783392",
			["calendarclock"] = "rbxassetid://10709783577",
			["calendardays"] = "rbxassetid://10709783673",
			["calendarheart"] = "rbxassetid://10709783835",
			["calendarminus"] = "rbxassetid://10709783959",
			["calendaroff"] = "rbxassetid://10709788784",
			["calendarplus"] = "rbxassetid://10709788937",
			["calendarrange"] = "rbxassetid://10709789053",
			["calendarsearch"] = "rbxassetid://10709789200",
			["calendarx"] = "rbxassetid://10709789407",
			["calendarx2"] = "rbxassetid://10709789329",
			["camera"] = "rbxassetid://10709789686",
			["cameraoff"] = "rbxassetid://10747822677",
			["car"] = "rbxassetid://10709789810",
			["carrot"] = "rbxassetid://10709789960",
			["cast"] = "rbxassetid://10709790097",
			["charge"] = "rbxassetid://10709790202",
			["check"] = "rbxassetid://10709790644",
			["checkcircle"] = "rbxassetid://10709790387",
			["checkcircle2"] = "rbxassetid://10709790298",
			["checksquare"] = "rbxassetid://10709790537",
			["chefhat"] = "rbxassetid://10709790757",
			["cherry"] = "rbxassetid://10709790875",
			["chevrondown"] = "rbxassetid://10709790948",
			["chevronfirst"] = "rbxassetid://10709791015",
			["chevronlast"] = "rbxassetid://10709791130",
			["chevronleft"] = "rbxassetid://10709791281",
			["chevronright"] = "rbxassetid://10709791437",
			["chevronup"] = "rbxassetid://10709791523",
			["chevronsdown"] = "rbxassetid://10709796864",
			["chevronsdownup"] = "rbxassetid://10709791632",
			["chevronsleft"] = "rbxassetid://10709797151",
			["chevronsleftright"] = "rbxassetid://10709797006",
			["chevronsright"] = "rbxassetid://10709797382",
			["chevronsrightleft"] = "rbxassetid://10709797274",
			["chevronsup"] = "rbxassetid://10709797622",
			["chevronsupdown"] = "rbxassetid://10709797508",
			["chrome"] = "rbxassetid://10709797725",
			["circle"] = "rbxassetid://10709798174",
			["circledot"] = "rbxassetid://10709797837",
			["circleellipsis"] = "rbxassetid://10709797985",
			["circleslashed"] = "rbxassetid://10709798100",
			["citrus"] = "rbxassetid://10709798276",
			["clapperboard"] = "rbxassetid://10709798350",
			["clipboard"] = "rbxassetid://10709799288",
			["clipboardcheck"] = "rbxassetid://10709798443",
			["clipboardcopy"] = "rbxassetid://10709798574",
			["clipboardedit"] = "rbxassetid://10709798682",
			["clipboardlist"] = "rbxassetid://10709798792",
			["clipboardsignature"] = "rbxassetid://10709798890",
			["clipboardtype"] = "rbxassetid://10709798999",
			["clipboardx"] = "rbxassetid://10709799124",
			["clock"] = "rbxassetid://10709805144",
			["clock1"] = "rbxassetid://10709799535",
			["clock10"] = "rbxassetid://10709799718",
			["clock11"] = "rbxassetid://10709799818",
			["clock12"] = "rbxassetid://10709799962",
			["clock2"] = "rbxassetid://10709803876",
			["clock3"] = "rbxassetid://10709803989",
			["clock4"] = "rbxassetid://10709804164",
			["clock5"] = "rbxassetid://10709804291",
			["clock6"] = "rbxassetid://10709804435",
			["clock7"] = "rbxassetid://10709804599",
			["clock8"] = "rbxassetid://10709804784",
			["clock9"] = "rbxassetid://10709804996",
			["cloud"] = "rbxassetid://10709806740",
			["cloudcog"] = "rbxassetid://10709805262",
			["clouddrizzle"] = "rbxassetid://10709805371",
			["cloudfog"] = "rbxassetid://10709805477",
			["cloudhail"] = "rbxassetid://10709805596",
			["cloudlightning"] = "rbxassetid://10709805727",
			["cloudmoon"] = "rbxassetid://10709805942",
			["cloudmoonrain"] = "rbxassetid://10709805838",
			["cloudoff"] = "rbxassetid://10709806060",
			["cloudrain"] = "rbxassetid://10709806277",
			["cloudrainwind"] = "rbxassetid://10709806166",
			["cloudsnow"] = "rbxassetid://10709806374",
			["cloudsun"] = "rbxassetid://10709806631",
			["cloudsunrain"] = "rbxassetid://10709806475",
			["cloudy"] = "rbxassetid://10709806859",
			["clover"] = "rbxassetid://10709806995",
			["code"] = "rbxassetid://10709810463",
			["code2"] = "rbxassetid://10709807111",
			["codepen"] = "rbxassetid://10709810534",
			["codesandbox"] = "rbxassetid://10709810676",
			["coffee"] = "rbxassetid://10709810814",
			["cog"] = "rbxassetid://10709810948",
			["coins"] = "rbxassetid://10709811110",
			["columns"] = "rbxassetid://10709811261",
			["command"] = "rbxassetid://10709811365",
			["compass"] = "rbxassetid://10709811445",
			["component"] = "rbxassetid://10709811595",
			["conciergebell"] = "rbxassetid://10709811706",
			["connection"] = "rbxassetid://10747361219",
			["contact"] = "rbxassetid://10709811834",
			["contrast"] = "rbxassetid://10709811939",
			["cookie"] = "rbxassetid://10709812067",
			["copy"] = "rbxassetid://10709812159",
			["copyleft"] = "rbxassetid://10709812251",
			["copyright"] = "rbxassetid://10709812311",
			["cornerdownleft"] = "rbxassetid://10709812396",
			["cornerdownright"] = "rbxassetid://10709812485",
			["cornerleftdown"] = "rbxassetid://10709812632",
			["cornerleftup"] = "rbxassetid://10709812784",
			["cornerrightdown"] = "rbxassetid://10709812939",
			["cornerrightup"] = "rbxassetid://10709813094",
			["cornerupleft"] = "rbxassetid://10709813185",
			["cornerupright"] = "rbxassetid://10709813281",
			["cpu"] = "rbxassetid://10709813383",
			["croissant"] = "rbxassetid://10709818125",
			["crop"] = "rbxassetid://10709818245",
			["cross"] = "rbxassetid://10709818399",
			["crosshair"] = "rbxassetid://10709818534",
			["crown"] = "rbxassetid://10709818626",
			["cupsoda"] = "rbxassetid://10709818763",
			["curlybraces"] = "rbxassetid://10709818847",
			["currency"] = "rbxassetid://10709818931",
			["database"] = "rbxassetid://10709818996",
			["delete"] = "rbxassetid://10709819059",
			["diamond"] = "rbxassetid://10709819149",
			["dice1"] = "rbxassetid://10709819266",
			["dice2"] = "rbxassetid://10709819361",
			["dice3"] = "rbxassetid://10709819508",
			["dice4"] = "rbxassetid://10709819670",
			["dice5"] = "rbxassetid://10709819801",
			["dice6"] = "rbxassetid://10709819896",
			["dices"] = "rbxassetid://10723343321",
			["diff"] = "rbxassetid://10723343416",
			["disc"] = "rbxassetid://10723343537",
			["divide"] = "rbxassetid://10723343805",
			["dividecircle"] = "rbxassetid://10723343636",
			["dividesquare"] = "rbxassetid://10723343737",
			["dollarsign"] = "rbxassetid://10723343958",
			["download"] = "rbxassetid://10723344270",
			["downloadcloud"] = "rbxassetid://10723344088",
			["droplet"] = "rbxassetid://10723344432",
			["droplets"] = "rbxassetid://10734883356",
			["drumstick"] = "rbxassetid://10723344737",
			["edit"] = "rbxassetid://10734883598",
			["edit2"] = "rbxassetid://10723344885",
			["edit3"] = "rbxassetid://10723345088",
			["egg"] = "rbxassetid://10723345518",
			["eggfried"] = "rbxassetid://10723345347",
			["electricity"] = "rbxassetid://10723345749",
			["electricityoff"] = "rbxassetid://10723345643",
			["equal"] = "rbxassetid://10723345990",
			["equalnot"] = "rbxassetid://10723345866",
			["eraser"] = "rbxassetid://10723346158",
			["euro"] = "rbxassetid://10723346372",
			["expand"] = "rbxassetid://10723346553",
			["externallink"] = "rbxassetid://10723346684",
			["eye"] = "rbxassetid://10723346959",
			["eyeoff"] = "rbxassetid://10723346871",
			["factory"] = "rbxassetid://10723347051",
			["fan"] = "rbxassetid://10723354359",
			["fastforward"] = "rbxassetid://10723354521",
			["feather"] = "rbxassetid://10723354671",
			["figma"] = "rbxassetid://10723354801",
			["file"] = "rbxassetid://10723374641",
			["filearchive"] = "rbxassetid://10723354921",
			["fileaudio"] = "rbxassetid://10723355148",
			["fileaudio2"] = "rbxassetid://10723355026",
			["fileaxis3d"] = "rbxassetid://10723355272",
			["filebadge"] = "rbxassetid://10723355622",
			["filebadge2"] = "rbxassetid://10723355451",
			["filebarchart"] = "rbxassetid://10723355887",
			["filebarchart2"] = "rbxassetid://10723355746",
			["filebox"] = "rbxassetid://10723355989",
			["filecheck"] = "rbxassetid://10723356210",
			["filecheck2"] = "rbxassetid://10723356100",
			["fileclock"] = "rbxassetid://10723356329",
			["filecode"] = "rbxassetid://10723356507",
			["filecog"] = "rbxassetid://10723356830",
			["filecog2"] = "rbxassetid://10723356676",
			["filediff"] = "rbxassetid://10723357039",
			["filedigit"] = "rbxassetid://10723357151",
			["filedown"] = "rbxassetid://10723357322",
			["fileedit"] = "rbxassetid://10723357495",
			["fileheart"] = "rbxassetid://10723357637",
			["fileimage"] = "rbxassetid://10723357790",
			["fileinput"] = "rbxassetid://10723357933",
			["filejson"] = "rbxassetid://10723364435",
			["filejson2"] = "rbxassetid://10723364361",
			["filekey"] = "rbxassetid://10723364605",
			["filekey2"] = "rbxassetid://10723364515",
			["filelinechart"] = "rbxassetid://10723364725",
			["filelock"] = "rbxassetid://10723364957",
			["filelock2"] = "rbxassetid://10723364861",
			["fileminus"] = "rbxassetid://10723365254",
			["fileminus2"] = "rbxassetid://10723365086",
			["fileoutput"] = "rbxassetid://10723365457",
			["filepiechart"] = "rbxassetid://10723365598",
			["fileplus"] = "rbxassetid://10723365877",
			["fileplus2"] = "rbxassetid://10723365766",
			["filequestion"] = "rbxassetid://10723365987",
			["filescan"] = "rbxassetid://10723366167",
			["filesearch"] = "rbxassetid://10723366550",
			["filesearch2"] = "rbxassetid://10723366340",
			["filesignature"] = "rbxassetid://10723366741",
			["filespreadsheet"] = "rbxassetid://10723366962",
			["filesymlink"] = "rbxassetid://10723367098",
			["fileterminal"] = "rbxassetid://10723367244",
			["filetext"] = "rbxassetid://10723367380",
			["filetype"] = "rbxassetid://10723367606",
			["filetype2"] = "rbxassetid://10723367509",
			["fileup"] = "rbxassetid://10723367734",
			["filevideo"] = "rbxassetid://10723373884",
			["filevideo2"] = "rbxassetid://10723367834",
			["filevolume"] = "rbxassetid://10723374172",
			["filevolume2"] = "rbxassetid://10723374030",
			["filewarning"] = "rbxassetid://10723374276",
			["filex"] = "rbxassetid://10723374544",
			["filex2"] = "rbxassetid://10723374378",
			["files"] = "rbxassetid://10723374759",
			["film"] = "rbxassetid://10723374981",
			["filter"] = "rbxassetid://10723375128",
			["fingerprint"] = "rbxassetid://10723375250",
			["flag"] = "rbxassetid://10723375890",
			["flagoff"] = "rbxassetid://10723375443",
			["flagtriangleleft"] = "rbxassetid://10723375608",
			["flagtriangleright"] = "rbxassetid://10723375727",
			["flame"] = "rbxassetid://10723376114",
			["flashlight"] = "rbxassetid://10723376471",
			["flashlightoff"] = "rbxassetid://10723376365",
			["flaskconical"] = "rbxassetid://10734883986",
			["flaskround"] = "rbxassetid://10723376614",
			["fliphorizontal"] = "rbxassetid://10723376884",
			["fliphorizontal2"] = "rbxassetid://10723376745",
			["flipvertical"] = "rbxassetid://10723377180",
			["flipvertical2"] = "rbxassetid://10723377011",
			["flower"] = "rbxassetid://10723377317",
			["folder"] = "rbxassetid://10723377708",
			["foldercheck"] = "rbxassetid://10723377395",
			["folderminus"] = "rbxassetid://10723377508",
			["folderopen"] = "rbxassetid://10723377636",
			["folderplus"] = "rbxassetid://10723377800",
			["folderx"] = "rbxassetid://10723377922",
			["forklift"] = "rbxassetid://10723378037",
			["framer"] = "rbxassetid://10723378129",
			["frown"] = "rbxassetid://10723378276",
			["fuel"] = "rbxassetid://10723378415",
			["function"] = "rbxassetid://10723378546",
			["galleryhorizontal"] = "rbxassetid://10723384260",
			["galleryhorizontalend"] = "rbxassetid://10723384102",
			["galleryvertical"] = "rbxassetid://10723384501",
			["galleryverticalend"] = "rbxassetid://10723384358",
			["gamepad"] = "rbxassetid://10723384639",
			["ganttchart"] = "rbxassetid://10723384752",
			["gaugemax"] = "rbxassetid://10723384879",
			["gaugemin"] = "rbxassetid://10723385038",
			["gem"] = "rbxassetid://10723385154",
			["ghost"] = "rbxassetid://10723385250",
			["gift"] = "rbxassetid://10723385390",
			["gitbranch"] = "rbxassetid://10723385558",
			["gitbranchplus"] = "rbxassetid://10723385474",
			["gitcommit"] = "rbxassetid://10723385686",
			["gitcompare"] = "rbxassetid://10723385800",
			["gitfork"] = "rbxassetid://10723385896",
			["gitmerge"] = "rbxassetid://10723386016",
			["gitpullrequest"] = "rbxassetid://10723386121",
			["gitpullrequestclosed"] = "rbxassetid://10723386221",
			["github"] = "rbxassetid://10723386348",
			["gitlab"] = "rbxassetid://10723386470",
			["glasswater"] = "rbxassetid://10723386576",
			["globe"] = "rbxassetid://10723386708",
			["graduationcap"] = "rbxassetid://10723386866",
			["grape"] = "rbxassetid://10723386993",
			["grid"] = "rbxassetid://10723387114",
			["grip"] = "rbxassetid://10723387343",
			["gripvertical"] = "rbxassetid://10723387228",
			["grouphorizontal"] = "rbxassetid://10723387609",
			["groupvertical"] = "rbxassetid://10723387756",
			["h1"] = "rbxassetid://10723387864",
			["h2"] = "rbxassetid://10723387949",
			["h3"] = "rbxassetid://10723388062",
			["h4"] = "rbxassetid://10723388151",
			["h5"] = "rbxassetid://10723388273",
			["h6"] = "rbxassetid://10723388372",
			["hand"] = "rbxassetid://10723389146",
			["handbag"] = "rbxassetid://10723388497",
			["handshake"] = "rbxassetid://10723388588",
			["harddrive"] = "rbxassetid://10723388837",
			["harddriveupload"] = "rbxassetid://10723388711",
			["hardhat"] = "rbxassetid://10723388960",
			["hash"] = "rbxassetid://10723389052",
			["headphones"] = "rbxassetid://10723389230",
			["heart"] = "rbxassetid://10723389500",
			["heartcrack"] = "rbxassetid://10723389332",
			["heartpulse"] = "rbxassetid://10723389650",
			["helpcircle"] = "rbxassetid://10723395991",
			["highlighter"] = "rbxassetid://10723396113",
			["history"] = "rbxassetid://10723396253",
			["home"] = "rbxassetid://10723396340",
			["icecream"] = "rbxassetid://10723396440",
			["image"] = "rbxassetid://10723396590",
			["import"] = "rbxassetid://10723396739",
			["inbox"] = "rbxassetid://10723396866",
			["indent"] = "rbxassetid://10723396996",
			["indianrupee"] = "rbxassetid://10723397125",
			["infinity"] = "rbxassetid://10723397228",
			["info"] = "rbxassetid://10723397334",
			["instagram"] = "rbxassetid://10723397444",
			["italic"] = "rbxassetid://10723397576",
			["japaneseyen"] = "rbxassetid://10723397686",
			["key"] = "rbxassetid://10723397839",
			["keyboard"] = "rbxassetid://10723398016",
			["lamp"] = "rbxassetid://10723398284",
			["lampdesk"] = "rbxassetid://10723398114",
			["lampletters"] = "rbxassetid://10723398394",
			["lampceiling"] = "rbxassetid://10723398501",
			["lampshade"] = "rbxassetid://10723398606",
			["languages"] = "rbxassetid://10723398701",
			["laptop"] = "rbxassetid://10723398864",
			["lasso"] = "rbxassetid://10723399009",
			["lassoselect"] = "rbxassetid://10723399092",
			["laugh"] = "rbxassetid://10723399222",
			["layers"] = "rbxassetid://10723399351",
			["layoutdashboard"] = "rbxassetid://10723399623",
			["layoutgrid"] = "rbxassetid://10723399513",
			["layoutlist"] = "rbxassetid://10723399720",
			["layoutpanelleft"] = "rbxassetid://10723399849",
			["layoutpaneltop"] = "rbxassetid://10723399990",
			["layouttemplate"] = "rbxassetid://10723400109",
			["leaf"] = "rbxassetid://10723400262",
			["lemon"] = "rbxassetid://10723400350",
			["library"] = "rbxassetid://10723400492",
			["lightbulb"] = "rbxassetid://10723400732",
			["lightbulboff"] = "rbxassetid://10723400582",
			["linechart"] = "rbxassetid://10723400898",
			["link"] = "rbxassetid://10723401140",
			["link2"] = "rbxassetid://10723400994",
			["link3"] = "rbxassetid://10723401062",
			["linkbreak"] = "rbxassetid://10723401297",
			["linkedin"] = "rbxassetid://10723401416",
			["list"] = "rbxassetid://10723401662",
			["listchecks"] = "rbxassetid://10723401497",
			["listend"] = "rbxassetid://10723401768",
			["listminus"] = "rbxassetid://10723401880",
			["listordered"] = "rbxassetid://10723401994",
			["listplus"] = "rbxassetid://10723402095",
			["liststart"] = "rbxassetid://10723402213",
			["listx"] = "rbxassetid://10723402302",
			["loader"] = "rbxassetid://10723402506",
			["loader2"] = "rbxassetid://10723402409",
			["locatetrack"] = "rbxassetid://10723402636",
			["lock"] = "rbxassetid://10723402804",
			["lockopen"] = "rbxassetid://10723402928",
			["logincircle"] = "rbxassetid://10723403164",
			["logoutcircle"] = "rbxassetid://10723403046",
			["lucide"] = "rbxassetid://10723403328",
			["magnet"] = "rbxassetid://10723403444",
			["mail"] = "rbxassetid://10723403698",
			["mailcheck"] = "rbxassetid://10723403565",
			["mailminus"] = "rbxassetid://10723403816",
			["mailopen"] = "rbxassetid://10723403915",
			["mailplus"] = "rbxassetid://10723404021",
			["mailx"] = "rbxassetid://10723404149",
			["map"] = "rbxassetid://10723404457",
			["map2"] = "rbxassetid://10723404289",
			["maximize"] = "rbxassetid://10723404764",
			["maximize2"] = "rbxassetid://10723404652",
			["medal"] = "rbxassetid://10723404868",
			["megaphone"] = "rbxassetid://10723405021",
			["meh"] = "rbxassetid://10723405103",
			["menu"] = "rbxassetid://10723405307",
			["messagetext"] = "rbxassetid://10723405524",
			["messagecircle"] = "rbxassetid://10723405400",
			["mic"] = "rbxassetid://10723405822",
			["micoff"] = "rbxassetid://10723405663",
			["minimize"] = "rbxassetid://10723406001",
			["minimize2"] = "rbxassetid://10723405908",
			["minus"] = "rbxassetid://10723406253",
			["minuscircle"] = "rbxassetid://10723406089",
			["minussquare"] = "rbxassetid://10723406346",
			["monitor"] = "rbxassetid://10723406734",
			["monitoroff"] = "rbxassetid://10723406437",
			["monitorpause"] = "rbxassetid://10723406830",
			["monitorplay"] = "rbxassetid://10723406935",
			["monitorstop"] = "rbxassetid://10723407040",
			["moon"] = "rbxassetid://10723407137",
			["mountain"] = "rbxassetid://10723407335",
			["mountain2"] = "rbxassetid://10723407222",
			["mouse"] = "rbxassetid://10723407421",
			["move"] = "rbxassetid://10723407519",
			["music"] = "rbxassetid://10723407639",
			["navigation"] = "rbxassetid://10723407786",
			["navigation2"] = "rbxassetid://10723407887",
			["network"] = "rbxassetid://10723408010",
			["newspaper"] = "rbxassetid://10723408101",
			["nut"] = "rbxassetid://10723408226",
			["octagon"] = "rbxassetid://10723408331",
			["option"] = "rbxassetid://10723408435",
			["package"] = "rbxassetid://10723408665",
			["packagecheck"] = "rbxassetid://10723408544",
			["packageopen"] = "rbxassetid://10723408796",
			["packagex"] = "rbxassetid://10723408929",
			["palette"] = "rbxassetid://10723409051",
			["panelleft"] = "rbxassetid://10723409166",
			["panelright"] = "rbxassetid://10723409277",
			["paperclip"] = "rbxassetid://10723409395",
			["parentheses"] = "rbxassetid://10723409497",
			["partyface"] = "rbxassetid://10723409641",
			["pause"] = "rbxassetid://10723409848",
			["pausecircle"] = "rbxassetid://10723409740",
			["pauseoctagon"] = "rbxassetid://10723409949",
			["pen"] = "rbxassetid://10723410190",
			["pencil"] = "rbxassetid://10723410077",
			["phone"] = "rbxassetid://10723410427",
			["phonecall"] = "rbxassetid://10723410292",
			["phoneforwarded"] = "rbxassetid://10723410508",
			["phoneincoming"] = "rbxassetid://10723410631",
			["phoneincoming2"] = "rbxassetid://10723410563",
			["phoneoutgoing"] = "rbxassetid://10723410712",
			["phoneoutgoing2"] = "rbxassetid://10723410769",
			["phonepause"] = "rbxassetid://10723410887",
			["phonex"] = "rbxassetid://10723411002",
			["phonex2"] = "rbxassetid://10723410931",
			["pictureinpicture"] = "rbxassetid://10723411202",
			["pictureinpicture2"] = "rbxassetid://10723411107",
			["piechart"] = "rbxassetid://10723411327",
			["piggybank"] = "rbxassetid://10723411470",
			["pin"] = "rbxassetid://10723411624",
			["pinpoint"] = "rbxassetid://10723411708",
			["plane"] = "rbxassetid://10723411874",
			["play"] = "rbxassetid://10723412023",
			["playcircle"] = "rbxassetid://10723411942",
			["plug"] = "rbxassetid://10723412151",
			["plug2"] = "rbxassetid://10723412239",
			["plus"] = "rbxassetid://10723412502",
			["pluscircle"] = "rbxassetid://10723412353",
			["plussquare"] = "rbxassetid://10723412610",
			["pocket"] = "rbxassetid://10723412708",
			["podcast"] = "rbxassetid://10723412852",
			["pointer"] = "rbxassetid://10723412952",
			["poundsterling"] = "rbxassetid://10723413063",
			["power"] = "rbxassetid://10723413158",
			["poweroff"] = "rbxassetid://10723413243",
			["printer"] = "rbxassetid://10723413346",
			["qr"] = "rbxassetid://10723413444",
			["quote"] = "rbxassetid://10723413554",
			["radiotower"] = "rbxassetid://10723413727",
			["rat"] = "rbxassetid://10723413867",
			["redo"] = "rbxassetid://10723414002",
			["refreshccw"] = "rbxassetid://10723414138",
			["refreshcw"] = "rbxassetid://10723414234",
			["removeregular"] = "rbxassetid://10734887309",
			["repeat"] = "rbxassetid://10723414440",
			["repeat1"] = "rbxassetid://10723414339",
			["repeat2"] = "rbxassetid://10723414578",
			["replace"] = "rbxassetid://10723414704",
			["replaceall"] = "rbxassetid://10723414808",
			["reply"] = "rbxassetid://10723414963",
			["replyall"] = "rbxassetid://10723415053",
			["return"] = "rbxassetid://10723415256",
			["ribbon"] = "rbxassetid://10723415372",
			["rocket"] = "rbxassetid://10723415510",
			["rotateccw"] = "rbxassetid://10723415663",
			["rotatecw"] = "rbxassetid://10723415754",
			["router"] = "rbxassetid://10723415904",
			["rss"] = "rbxassetid://10723416035",
			["ruler"] = "rbxassetid://10723416173",
			["russianruble"] = "rbxassetid://10723416301",
			["save"] = "rbxassetid://10723416416",
			["scalemax"] = "rbxassetid://10723416568",
			["scalemin"] = "rbxassetid://10723416694",
			["scan"] = "rbxassetid://10723416805",
			["scanbarcode"] = "rbxassetid://10723417036",
			["scancode"] = "rbxassetid://10723416898",
			["scissors"] = "rbxassetid://10723417129",
			["screenrotation"] = "rbxassetid://10723417387",
			["screentext"] = "rbxassetid://10723417531",
			["search"] = "rbxassetid://10723417726",
			["send"] = "rbxassetid://10723417855",
			["separatorhorizontal"] = "rbxassetid://10723417950",
			["separatorvertical"] = "rbxassetid://10723418131",
			["server"] = "rbxassetid://10723418257",
			["settings"] = "rbxassetid://10723418579",
			["settings2"] = "rbxassetid://10723418388",
			["share"] = "rbxassetid://10723418721",
			["share2"] = "rbxassetid://10723418659",
			["shield"] = "rbxassetid://10723419082",
			["shieldalert"] = "rbxassetid://10723418837",
			["shieldoff"] = "rbxassetid://10723418939",
			["shoppingbag"] = "rbxassetid://10723419266",
			["shoppingcart"] = "rbxassetid://10723419385",
			["shovel"] = "rbxassetid://10723419491",
			["shrink"] = "rbxassetid://10723419597",
			["sidebar"] = "rbxassetid://10723419828",
			["sidebarleft"] = "rbxassetid://10723419717",
			["sidebarright"] = "rbxassetid://10723419934",
			["siren"] = "rbxassetid://10723420042",
			["skipback"] = "rbxassetid://10723420172",
			["skipforward"] = "rbxassetid://10723420287",
			["skull"] = "rbxassetid://10723420427",
			["slack"] = "rbxassetid://10723420546",
			["slash"] = "rbxassetid://10723420658",
			["sliders"] = "rbxassetid://10723420803",
			["slidershorizontal"] = "rbxassetid://10723420917",
			["smartphone"] = "rbxassetid://10723421111",
			["smartphonecharging"] = "rbxassetid://10723420993",
			["smile"] = "rbxassetid://10723421255",
			["snowflake"] = "rbxassetid://10723421422",
			["sortasc"] = "rbxassetid://10723421528",
			["sortdesc"] = "rbxassetid://10723421671",
			["speaker"] = "rbxassetid://10723421774",
			["square"] = "rbxassetid://10723421908",
			["squarecheck"] = "rbxassetid://10723421867",
			["squarecross"] = "rbxassetid://10723422026",
			["squareminus"] = "rbxassetid://10723422176",
			["squareoff"] = "rbxassetid://10723422271",
			["squareplus"] = "rbxassetid://10723422394",
			["star"] = "rbxassetid://10723422709",
			["starhalf"] = "rbxassetid://10723422502",
			["staroff"] = "rbxassetid://10723422591",
			["stepback"] = "rbxassetid://10723422830",
			["stepforward"] = "rbxassetid://10723422964",
			["stethoscope"] = "rbxassetid://10723423140",
			["stickyhand"] = "rbxassetid://10723423277",
			["sticker"] = "rbxassetid://10723423423",
			["stopcircle"] = "rbxassetid://10723423531",
			["sun"] = "rbxassetid://10723423689",
			["sunrise"] = "rbxassetid://10723423805",
			["sunset"] = "rbxassetid://10723423945",
			["switch"] = "rbxassetid://10723424103",
			["sword"] = "rbxassetid://10723424198",
			["tag"] = "rbxassetid://10723424364",
			["tablet"] = "rbxassetid://10723424263",
			["target"] = "rbxassetid://10723424483",
			["telescope"] = "rbxassetid://10723424594",
			["tent"] = "rbxassetid://10723424754",
			["terminal"] = "rbxassetid://10723424911",
			["terminalsquare"] = "rbxassetid://10723425000",
			["testtube"] = "rbxassetid://10723425217",
			["testtube2"] = "rbxassetid://10723425121",
			["textcursor"] = "rbxassetid://10723425330",
			["textselect"] = "rbxassetid://10723425445",
			["thermometer"] = "rbxassetid://10723425624",
			["thumbsdown"] = "rbxassetid://10723425785",
			["thumbsup"] = "rbxassetid://10723425946",
			["ticket"] = "rbxassetid://10723426065",
			["timer"] = "rbxassetid://10723426330",
			["timeroff"] = "rbxassetid://10723426176",
			["toggleleft"] = "rbxassetid://10723426500",
			["toggleright"] = "rbxassetid://10723426615",
			["tornado"] = "rbxassetid://10723426759",
			["toybrick"] = "rbxassetid://10723426868",
			["trash"] = "rbxassetid://10723427181",
			["trash2"] = "rbxassetid://10723427003",
			["trello"] = "rbxassetid://10723427339",
			["triangle"] = "rbxassetid://10723427497",
			["trophy"] = "rbxassetid://10723427613",
			["truck"] = "rbxassetid://10723427749",
			["turkishlira"] = "rbxassetid://10723427847",
			["tv"] = "rbxassetid://10723428078",
			["tv2"] = "rbxassetid://10723427954",
			["twitch"] = "rbxassetid://10723428205",
			["type"] = "rbxassetid://10723428312",
			["umbrella"] = "rbxassetid://10723428456",
			["underline"] = "rbxassetid://10723428615",
			["undo"] = "rbxassetid://10723428751",
			["unlink"] = "rbxassetid://10723428876",
			["unlink2"] = "rbxassetid://10723428989",
			["unlock"] = "rbxassetid://10723429114",
			["upload"] = "rbxassetid://10723429281",
			["uploadcloud"] = "rbxassetid://10723429402",
			["usb"] = "rbxassetid://10723429497",
			["user"] = "rbxassetid://10723429712",
			["usercheck"] = "rbxassetid://10723429598",
			["userminus"] = "rbxassetid://10723429815",
			["userplus"] = "rbxassetid://10723429944",
			["users"] = "rbxassetid://10723430177",
			["userx"] = "rbxassetid://10723430058",
			["variable"] = "rbxassetid://10723430337",
			["vegan"] = "rbxassetid://10723430466",
			["venndiagram"] = "rbxassetid://10723430635",
			["verified"] = "rbxassetid://10723430752",
			["vial"] = "rbxassetid://10723430857",
			["video"] = "rbxassetid://10723431057",
			["videocall"] = "rbxassetid://10723430939",
			["videocalloff"] = "rbxassetid://10723431189",
			["view"] = "rbxassetid://10723431320",
			["volumedown"] = "rbxassetid://10723431627",
			["volumex"] = "rbxassetid://10723431526",
			["volumemute"] = "rbxassetid://10723431417",
			["volumeup"] = "rbxassetid://10723431777",
			["wallet"] = "rbxassetid://10723431899",
			["wand"] = "rbxassetid://10723432049",
			["waves"] = "rbxassetid://10723432247",
			["webcam"] = "rbxassetid://10723432360",
			["webhook"] = "rbxassetid://10723432483",
			["wheat"] = "rbxassetid://10723432612",
			["wifi"] = "rbxassetid://10723432766",
			["wifioff"] = "rbxassetid://10723432857",
			["wind"] = "rbxassetid://10723432970",
			["x"] = "rbxassetid://10723433156",
			["xcircle"] = "rbxassetid://10723433066",
			["xsquare"] = "rbxassetid://10723433256",
			["youtube"] = "rbxassetid://10723433379",
			["zap"] = "rbxassetid://10723433504",
			["zapoff"] = "rbxassetid://10723433433",
			["zoomout"] = "rbxassetid://10723433605",
			["zoomoutcircle"] = "rbxassetid://10723433728",
			["zoomoutsquare"] = "rbxassetid://10723433824",
			["zoomincircle"] = "rbxassetid://10723433947",
			["zoomin"] = "rbxassetid://10723434101",
			["zoominsquare"] = "rbxassetid://10723434241"
		}
	})()
}

local function Create(Instance, Parent, Properties)
	local NewInstance = Instance.new(Instance)
	NewInstance.Parent = Parent

	if Properties then
		for Index, Value in pairs(Properties) do
			NewInstance[Index] = Value
		end
	end
	return NewInstance
end

local function Make(Instance, Parent, UDim, UDim2, Clip)
	if Instance == "Corner" then
		return Create("UICorner", Parent, {
			CornerRadius = UDim
		})
	elseif Instance == "Layout" then
		return Create("UIListLayout", Parent, {
			Padding = UDim2,
			SortOrder = Enum.SortOrder.LayoutOrder,
			FillDirection = Enum.FillDirection.Vertical,
			HorizontalAlignment = Enum.HorizontalAlignment.Left,
			VerticalAlignment = Enum.VerticalAlignment.Top
		})
	elseif Instance == "Grid" then
		return Create("UIGridLayout", Parent, {
			CellPadding = UDim2,
			SortOrder = Enum.SortOrder.LayoutOrder,
			FillDirection = Enum.FillDirection.Horizontal,
			HorizontalAlignment = Enum.HorizontalAlignment.Left,
			VerticalAlignment = Enum.VerticalAlignment.Top,
			CellSize = UDim2.new(0.5, 0, 0, 30)
		})
	elseif Instance == "Aspect" then
		return Create("UIAspectRatioConstraint", Parent, {
			AspectRatio = UDim
		})
	elseif Instance == "Stroke" then
		return Create("UIStroke", Parent, {
			Color = redzlib.Themes[redzlib.Save.Theme]["Color Stroke"],
			Transparency = 0.5,
			Thickness = UDim
		})
	elseif Instance == "Gradient" then
		return Create("UIGradient", Parent, {
			Color = redzlib.Themes[redzlib.Save.Theme]["Color Hub 1"],
			Transparency = UDim
		})
	elseif Instance == "List" then
		return Create("UIListLayout", Parent, {
			Padding = UDim2,
			SortOrder = Enum.SortOrder.LayoutOrder,
			FillDirection = Enum.FillDirection.Vertical,
			HorizontalAlignment = Enum.HorizontalAlignment.Left,
			VerticalAlignment = Enum.VerticalAlignment.Top
		})
	elseif Instance == "Size" then
		return Create("UISizeConstraint", Parent, {
			MinSize = UDim2,
			MaxSize = UDim2
		})
	end
end

local function SetProps(Instance, Properties)
	for Index, Value in pairs(Properties) do
		Instance[Index] = Value
	end
end

local function SetColor(Instance, Index)
	TweenService:Create(Instance, TweenInfo.new(0.1), {
		Color = redzlib.Themes[redzlib.Save.Theme][Index]
	}):Play()
end

local function SetBackgroundColor(Instance, Index)
	TweenService:Create(Instance, TweenInfo.new(0.1), {
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme][Index]
	}):Play()
end

local function SetTextColor(Instance, Index)
	TweenService:Create(Instance, TweenInfo.new(0.1), {
		TextColor3 = redzlib.Themes[redzlib.Save.Theme][Index]
	}):Play()
end

local function SetTransparency(Instance, Transparency)
	TweenService:Create(Instance, TweenInfo.new(0.1), {
		BackgroundTransparency = Transparency
	}):Play()
end

local function SetGradient(Instance, Index)
	TweenService:Create(Instance, TweenInfo.new(0.1), {
		Color = redzlib.Themes[redzlib.Save.Theme][Index]
	}):Play()
end

local function SetRotation(Instance, Rotation)
	TweenService:Create(Instance, TweenInfo.new(0.1), {
		Rotation = Rotation
	}):Play()
end

local function SetPosition(Instance, Position)
	TweenService:Create(Instance, TweenInfo.new(0.1), {
		Position = Position
	}):Play()
end

local function SetVisible(Instance, Transparency, Visible)
	if Visible == true then
		Instance.Visible = true
	end
	TweenService:Create(Instance, TweenInfo.new(0.1), {
		BackgroundTransparency = Transparency
	}):Play()
	if Visible == false then
		Instance.Visible = false
	end
end

local function SetSize(Instance, Size)
	TweenService:Create(Instance, TweenInfo.new(0.1), {
		Size = Size
	}):Play()
end

local function SetSizeX(Instance, Size)
	TweenService:Create(Instance, TweenInfo.new(0.1), {
		Size = UDim2.new(Size, 0, Instance.Size.Y.Scale, Instance.Size.Y.Offset)
	}):Play()
end

local function GetNearest(Input)
	local Target
	local Distance = math.huge

	for _, Player in pairs(game.Players:GetPlayers()) do
		if Player.Character and Player.Character:FindFirstChild("HumanoidRootPart") and Player.Name ~= game.Players.LocalPlayer.Name then
			local PlayerPosition = Player.Character.HumanoidRootPart.Position
			local LocalPlayerPosition = game.Players.LocalPlayer.Character.HumanoidRootPart.Position
			local CurrentDistance = (PlayerPosition - LocalPlayerPosition).Magnitude

			if CurrentDistance < Distance and Player.Team ~= game.Players.LocalPlayer.Team then
				Distance = CurrentDistance
				Target = Player
			end
		end
	end

	return Target
end

local function GetSettings(Setting)
	if redzlib.Settings[Setting] then
		return redzlib.Settings[Setting]
	else
		return nil
	end
end

local function GetElements(Element)
	if redzlib.Elements[Element] then
		return redzlib.Elements[Element]
	else
		return nil
	end
end

local function GetOptions(Option)
	if redzlib.Options[Option] then
		return redzlib.Options[Option]
	else
		return nil
	end
end

local function GetFlags(Flag)
	if redzlib.Flags[Flag] then
		return redzlib.Flags[Flag]
	else
		return nil
	end
end

local function UpdateMenu(Theme)
	for _, Instance in pairs(redzlib.Instances) do
		for Index, Object in pairs(Instance:GetChildren()) do
			if Object.Name == "Color" then
				SetColor(Object, "Color Theme")
			end
			if Object.Name == "ColorStroke" then
				SetColor(Object, "Color Stroke")
			end
			if Object.Name == "ColorHub1" then
				SetColor(Object, "Color Hub 1")
			end
			if Object.Name == "ColorHub2" then
				SetBackgroundColor(Object, "Color Hub 2")
			end
			if Object.Name == "ColorText" then
				SetTextColor(Object, "Color Text")
			end
			if Object.Name == "ColorDarkText" then
				SetTextColor(Object, "Color Dark Text")
			end
			if Object.Name == "Gradient" then
				SetGradient(Object, "Color Hub 1")
			end
		end
	end
	redzlib.Save.Theme = Theme
end

local function MakeTab(TabName)
	local NewTab = Create("TextButton", redzlib.Instances.TabsHolder, {
		Size = UDim2.new(1, 0, 0, 30),
		Text = "",
		BackgroundTransparency = 1
	})
	Make("List", NewTab, UDim2.new(0, 0, 0, 0))

	local TabHolder = Create("Frame", NewTab, {
		Size = UDim2.new(1, 0, 0, 30),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Hub 2"],
		BackgroundTransparency = 0
	})
	Make("Corner", TabHolder, UDim.new(0, 5))
	Make("Stroke", TabHolder, 1)

	local TabTitle = Create("TextLabel", TabHolder, {
		Size = UDim2.new(1, 0, 1, 0),
		Text = TabName,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"],
		BackgroundTransparency = 1
	})
	Create("Frame", TabHolder, {
		Name = "Color",
		Size = UDim2.new(0, 5, 0.7, 0),
		Position = UDim2.new(0, 5, 0.5, 0),
		AnchorPoint = Vector2.new(0, 0.5),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Theme"],
		BackgroundTransparency = 0
	})
	Make("Corner", TabHolder:FindFirstChild("Color"), UDim.new(0, 5))

	redzlib.Tabs[TabName] = NewTab

	NewTab.Activated:Connect(function()
		for _, Tab in pairs(redzlib.Tabs) do
			SetTransparency(Tab:FindFirstChild("Frame"), 0)
			SetTextColor(Tab:FindFirstChild("Frame"):FindFirstChild("TextLabel"), "Color Text")
			SetSize(Tab:FindFirstChild("Frame"):FindFirstChild("Color"), UDim2.new(0, 5, 0.7, 0))
		end
		SetTransparency(TabHolder, 0.2)
		SetTextColor(TabTitle, "Color Theme")
		SetSize(TabHolder:FindFirstChild("Color"), UDim2.new(0, 5, 1, 0))
	end)
	return NewTab
end

local function MakeSection(Tab, SectionName)
	local Section = Create("Frame", Tab, {
		Size = UDim2.new(1, 0, 0, 0),
		BackgroundTransparency = 1
	})
	Make("List", Section, UDim2.new(0, 0, 0, 0))
	
	local SectionTitle = Create("TextLabel", Section, {
		Size = UDim2.new(1, 0, 0, 20),
		Text = SectionName,
		Font = Enum.Font.GothamBold,
		TextSize = 16,
		TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"],
		BackgroundTransparency = 1
	})
	Create("Frame", Section, {
		Size = UDim2.new(1, 0, 0, 1),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Stroke"],
		BackgroundTransparency = 0
	})

	return Section
end

function redzlib.Utility.MakeToggle(Element, Section, Default)
	redzlib.Elements[Element] = Default
	
	local Frame = Create("Frame", Section, {
		Size = UDim2.new(1, 0, 0, 30),
		BackgroundTransparency = 1
	})
	
	local Toggle = Create("TextButton", Frame, {
		Size = UDim2.new(1, 0, 1, 0),
		Text = "",
		BackgroundTransparency = 1
	})
	
	local Title = Create("TextLabel", Frame, {
		Size = UDim2.new(1, 0, 1, 0),
		Text = Element,
		Font = Enum.Font.Gotham,
		TextSize = 14,
		TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"],
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left
	})
	
	local CheckBox = Create("Frame", Frame, {
		Size = UDim2.new(0, 20, 0, 20),
		Position = UDim2.new(1, -20, 0.5, 0),
		AnchorPoint = Vector2.new(1, 0.5),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Hub 2"],
		BackgroundTransparency = 0
	})
	Make("Corner", CheckBox, UDim.new(0, 5))
	Make("Stroke", CheckBox, 1)
	
	local CheckBoxColor = Create("Frame", CheckBox, {
		Name = "Color",
		Size = UDim2.new(0.8, 0, 0.8, 0),
		Position = UDim2.new(0.5, 0, 0.5, 0),
		AnchorPoint = Vector2.new(0.5, 0.5),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Theme"],
		BackgroundTransparency = 1
	})
	Make("Corner", CheckBoxColor, UDim.new(0, 5))

	if Default == true then
		SetTransparency(CheckBoxColor, 0)
	else
		SetTransparency(CheckBoxColor, 1)
	end
	
	Toggle.Activated:Connect(function()
		redzlib.Elements[Element] = not redzlib.Elements[Element]
		if redzlib.Elements[Element] == true then
			SetTransparency(CheckBoxColor, 0)
		else
			SetTransparency(CheckBoxColor, 1)
		end
	end)
end

function redzlib.Utility.MakeSlider(Element, Section, Default, Min, Max)
	redzlib.Elements[Element] = Default
	
	local Frame = Create("Frame", Section, {
		Size = UDim2.new(1, 0, 0, 40),
		BackgroundTransparency = 1
	})
	
	local Title = Create("TextLabel", Frame, {
		Size = UDim2.new(1, 0, 0, 20),
		Text = Element,
		Font = Enum.Font.Gotham,
		TextSize = 14,
		TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"],
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left
	})
	
	local Value = Create("TextLabel", Title, {
		Size = UDim2.new(0, 50, 1, 0),
		Position = UDim2.new(1, 0, 0, 0),
		AnchorPoint = Vector2.new(1, 0),
		Text = Default,
		Font = Enum.Font.Gotham,
		TextSize = 14,
		TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Dark Text"],
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Right
	})
	
	local BarHolder = Create("Frame", Frame, {
		Size = UDim2.new(1, 0, 0, 10),
		Position = UDim2.new(0, 0, 0, 25),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Hub 2"],
		BackgroundTransparency = 0
	})
	Make("Corner", BarHolder, UDim.new(0, 5))
	Make("Stroke", BarHolder, 1)
	
	local Bar = Create("Frame", BarHolder, {
		Name = "Color",
		Size = UDim2.new(Default / Max, 0, 1, 0),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Theme"],
		BackgroundTransparency = 0
	})
	Make("Corner", Bar, UDim.new(0, 5))
	
	local Button = Create("TextButton", BarHolder, {
		Size = UDim2.new(1, 0, 1, 0),
		Text = "",
		BackgroundTransparency = 1
	})
	
	local MouseDown = false
	Button.Activated:Connect(function()
		MouseDown = true
	end)
	
	UserInputService.InputEnded:Connect(function(Input)
		if Input.UserInputType == Enum.UserInputType.MouseButton1 then
			MouseDown = false
		end
	end)

	UserInputService.InputChanged:Connect(function(Input)
		if MouseDown and Input.UserInputType == Enum.UserInputType.MouseMovement then
			local MouseX = PlayerMouse.X
			local BarX = BarHolder.AbsolutePosition.X
			local BarWidth = BarHolder.AbsoluteSize.X
			
			local Percentage = math.clamp((MouseX - BarX) / BarWidth, 0, 1)
			local NewValue = math.floor(Percentage * Max)
			
			if NewValue < Min then
				NewValue = Min
			end
			
			redzlib.Elements[Element] = NewValue
			SetSizeX(Bar, Percentage)
			Value.Text = NewValue
		end
	end)
end

function redzlib.Utility.MakeButton(Element, Section, ButtonText, Function)
	local Frame = Create("Frame", Section, {
		Size = UDim2.new(1, 0, 0, 30),
		BackgroundTransparency = 1
	})

	local Button = Create("TextButton", Frame, {
		Size = UDim2.new(1, 0, 1, 0),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Theme"],
		BackgroundTransparency = 0,
		Text = ButtonText,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"]
	})
	Make("Corner", Button, UDim.new(0, 5))
	Make("Stroke", Button, 1)

	Button.Activated:Connect(function()
		Function()
	end)
end

function redzlib.Utility.MakeOption(Element, Section, Default, Options)
	redzlib.Options[Element] = Default
	
	local Frame = Create("Frame", Section, {
		Size = UDim2.new(1, 0, 0, 30),
		BackgroundTransparency = 1
	})
	
	local Title = Create("TextLabel", Frame, {
		Size = UDim2.new(1, 0, 1, 0),
		Text = Element,
		Font = Enum.Font.Gotham,
		TextSize = 14,
		TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"],
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left
	})
	
	local Option = Create("TextButton", Frame, {
		Size = UDim2.new(0, 100, 1, 0),
		Position = UDim2.new(1, 0, 0.5, 0),
		AnchorPoint = Vector2.new(1, 0.5),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Hub 2"],
		BackgroundTransparency = 0,
		Text = Default,
		Font = Enum.Font.Gotham,
		TextSize = 14,
		TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"]
	})
	Make("Corner", Option, UDim.new(0, 5))
	Make("Stroke", Option, 1)
	
	local Arrow = Create("ImageLabel", Option, {
		Size = UDim2.new(0, 12, 0, 12),
		Position = UDim2.new(1, -5, 0.5, 0),
		AnchorPoint = Vector2.new(1, 0.5),
		Image = redzlib.Icons["chevrondown"],
		ImageColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Dark Text"],
		BackgroundTransparency = 1
	})
	
	local List = Create("Frame", Frame, {
		Size = UDim2.new(0, 100, 0, 0),
		Position = UDim2.new(1, 0, 1, 5),
		AnchorPoint = Vector2.new(1, 0),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Hub 2"],
		BackgroundTransparency = 1,
		ClipsDescendants = true
	})
	Make("Corner", List, UDim.new(0, 5))
	Make("Stroke", List, 1)
	Make("List", List, UDim2.new(0, 0, 0, 0))
	
	local Active = false
	Option.Activated:Connect(function()
		Active = not Active
		if Active == true then
			SetTransparency(List, 0)
			SetSize(List, UDim2.new(0, 100, 0, #Options * 30))
			SetRotation(Arrow, 180)
		else
			SetTransparency(List, 1)
			SetSize(List, UDim2.new(0, 100, 0, 0))
			SetRotation(Arrow, 0)
		end
	end)

	for _, OptionText in pairs(Options) do
		local OptionButton = Create("TextButton", List, {
			Size = UDim2.new(1, 0, 0, 30),
			BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Hub 2"],
			BackgroundTransparency = 1,
			Text = OptionText,
			Font = Enum.Font.Gotham,
			TextSize = 14,
			TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"]
		})

		OptionButton.Activated:Connect(function()
			redzlib.Options[Element] = OptionText
			Option.Text = OptionText
			SetTransparency(List, 1)
			SetSize(List, UDim2.new(0, 100, 0, 0))
			SetRotation(Arrow, 0)
			Active = false
		end)
	end
end

function redzlib.Utility.MakeInvite(Invite, Desc)
	local Theme = redzlib.Themes[redzlib.Save.Theme]
	
	local FrameHolder = Create("Frame", redzlib.Instances.InvitesHolder, {
		Size = UDim2.new(0, 180, 0, 0),
		BackgroundColor3 = Theme["Color Hub 2"],
		BackgroundTransparency = 0,
		AutomaticSize = "Y"
	})
	Make("Corner", FrameHolder, UDim.new(0, 5))
	Make("Stroke", FrameHolder, 1)
	Make("List", FrameHolder, UDim2.new(0, 0, 0, 0))
	
	Create("Frame", FrameHolder, {
		Size = UDim2.new(1, 0, 0, 50),
		BackgroundTransparency = 1
	})

	Create("TextLabel", FrameHolder, {
		Size = UDim2.new(1, -10, 0, 20),
		Position = UDim2.new(0.5, 0, 0, 15),
		AnchorPoint = Vector2.new(0.5, 0),
		Text = "Invite",
		Font = Enum.Font.GothamBold,
		TextSize = 18,
		TextColor3 = Theme["Color Text"],
		BackgroundTransparency = 1
	})

	SetProps(Create("TextLabel", FrameHolder, {
		Size = UDim2.new(1, -10, 0, 12),
		AnchorPoint = Vector2.new(0.5, 0),
		Position = UDim2.new(0.5, 0, 0, 54),
		TextWrapped = "Y",
		AutomaticSize = "Y",
		Font = Enum.Font.Gotham,
		TextColor3 = Theme["Color Dark Text"],
		TextXAlignment = Enum.TextXAlignment.Left,
		BackgroundTransparency = 1,
		TextSize = 8,
		Text = Desc
	}), "DarkText")
			
	-- Start of MODIFIED JoinButton Block
			local DEFAULT_COLOR = Color3.fromRGB(50, 150, 50)
			local HOVER_COLOR = Color3.fromRGB(70, 180, 70) 
			local CLICKED_COLOR = Color3.fromRGB(100, 100, 100)
			local HOVER_TWEEN_INFO = TweenInfo.new(0.1, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)
			
			local JoinButton = Create("TextButton", FrameHolder, {
				Size = UDim2.new(1, -14, 0, 14), -- Reduced size (16 -> 14)
				AnchorPoint = Vector2.new(0.5, 1),
				Position = UDim2.new(0.5, 0, 1, -7),
				Text = "Join",
				Font = Enum.Font.GothamBold,
				TextSize = 12,
				TextColor3 = Color3.fromRGB(220, 220, 220),
				BackgroundColor3 = DEFAULT_COLOR -- Use defined color
			})
			Make("Corner", JoinButton, UDim.new(0, 5)) -- Kept small roundness

			-- Add Hover Animation
			local ClickDelay -- Must be defined before MouseEnter/MouseLeave logic can use it to check state
			
			JoinButton.MouseEnter:Connect(function()
				-- Only tween if the button is in its 'Join' state
				if not ClickDelay and JoinButton.Text == "Join" then
					TweenService:Create(JoinButton, HOVER_TWEEN_INFO, {BackgroundColor3 = HOVER_COLOR}):Play()
				end
			end)

			JoinButton.MouseLeave:Connect(function()
				-- Only tween back if the button is in its 'Join' state
				if not ClickDelay and JoinButton.Text == "Join" then
					TweenService:Create(JoinButton, HOVER_TWEEN_INFO, {BackgroundColor3 = DEFAULT_COLOR}):Play()
				end
			end)
			
			JoinButton.Activated:Connect(function()
				setclipboard(Invite)
				if ClickDelay then return end
				
				ClickDelay = true
				SetProps(JoinButton, {
					Text = "Copied to Clipboard",
					BackgroundColor3 = CLICKED_COLOR, -- Use defined color
					TextColor3 = Color3.fromRGB(150, 150, 150)
				})
				task.wait(5)
				
				SetProps(JoinButton, {
					Text = "Join",
					BackgroundColor3 = DEFAULT_COLOR, -- Use defined color for reset
					TextColor3 = Color3.fromRGB(220, 220, 220)
				})
				
				ClickDelay = nil
			end)
	-- End of MODIFIED JoinButton Block

	return FrameHolder
end

function redzlib.Utility.MakeFlag(Element, Section, Default)
	redzlib.Flags[Element] = Default
	
	local Frame = Create("Frame", Section, {
		Size = UDim2.new(1, 0, 0, 30),
		BackgroundTransparency = 1
	})
	
	local Toggle = Create("TextButton", Frame, {
		Size = UDim2.new(1, 0, 1, 0),
		Text = "",
		BackgroundTransparency = 1
	})
	
	local Title = Create("TextLabel", Frame, {
		Size = UDim2.new(1, 0, 1, 0),
		Text = Element,
		Font = Enum.Font.Gotham,
		TextSize = 14,
		TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"],
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left
	})
	
	local CheckBox = Create("Frame", Frame, {
		Size = UDim2.new(0, 20, 0, 20),
		Position = UDim2.new(1, -20, 0.5, 0),
		AnchorPoint = Vector2.new(1, 0.5),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Hub 2"],
		BackgroundTransparency = 0
	})
	Make("Corner", CheckBox, UDim.new(0, 5))
	Make("Stroke", CheckBox, 1)
	
	local CheckBoxColor = Create("Frame", CheckBox, {
		Name = "Color",
		Size = UDim2.new(0.8, 0, 0.8, 0),
		Position = UDim2.new(0.5, 0, 0.5, 0),
		AnchorPoint = Vector2.new(0.5, 0.5),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Theme"],
		BackgroundTransparency = 1
	})
	Make("Corner", CheckBoxColor, UDim.new(0, 5))

	if Default == true then
		SetTransparency(CheckBoxColor, 0)
	else
		SetTransparency(CheckBoxColor, 1)
	end
	
	Toggle.Activated:Connect(function()
		redzlib.Flags[Element] = not redzlib.Flags[Element]
		if redzlib.Flags[Element] == true then
			SetTransparency(CheckBoxColor, 0)
		else
			SetTransparency(CheckBoxColor, 1)
		end
	end)
end

function redzlib.Utility.MakeMenu(MenuName)
	local ScreenGui = Create("ScreenGui", CoreGui, {
		Name = MenuName,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
		ResetOnSpawn = false
	})

	local Menu = Create("Frame", ScreenGui, {
		Size = UDim2.new(0, redzlib.Save.UISize[1], 0, redzlib.Save.UISize[2]),
		Position = UDim2.new(0.5, 0, 0.5, 0),
		AnchorPoint = Vector2.new(0.5, 0.5),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Hub 2"],
		BackgroundTransparency = 0
	})
	redzlib.Instances.Menu = Menu
	Make("Corner", Menu, UDim.new(0, 5))
	Make("Stroke", Menu, 1)

	local TabsHolder = Create("Frame", Menu, {
		Size = UDim2.new(0, redzlib.Save.TabSize, 1, 0),
		BackgroundColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Hub 2"],
		BackgroundTransparency = 0
	})
	redzlib.Instances.TabsHolder = TabsHolder
	Create("Frame", TabsHolder, {
		Size = UDim2.new(1, 0, 1, 0),
		BackgroundTransparency = 1,
		LayoutOrder = 1
	})

	local ContentHolder = Create("Frame", Menu, {
		Size = UDim2.new(1, -redzlib.Save.TabSize, 1, -50),
		Position = UDim2.new(0, redzlib.Save.TabSize, 0, 50),
		BackgroundTransparency = 1
	})
	redzlib.Instances.ContentHolder = ContentHolder

	local Resize = Create("TextButton", Menu, {
		Size = UDim2.new(0, 10, 0, 10),
		Position = UDim2.new(1, 0, 1, 0),
		AnchorPoint = Vector2.new(1, 1),
		Text = "",
		BackgroundTransparency = 1
	})

	local Drag = Create("TextButton", Menu, {
		Size = UDim2.new(1, 0, 0, 30),
		Text = MenuName,
		Font = Enum.Font.GothamBold,
		TextSize = 18,
		TextColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"],
		BackgroundTransparency = 1
	})

	local MouseDown = false
	Drag.Activated:Connect(function()
		MouseDown = true
	end)

	UserInputService.InputEnded:Connect(function(Input)
		if Input.UserInputType == Enum.UserInputType.MouseButton1 then
			MouseDown = false
		end
	end)

	UserInputService.InputChanged:Connect(function(Input)
		if MouseDown and Input.UserInputType == Enum.UserInputType.MouseMovement then
			local MouseX = Input.Position.X
			local MouseY = Input.Position.Y
			
			local NewPosition = UDim2.new(0, MouseX - Menu.AbsoluteSize.X / 2, 0, MouseY - Menu.AbsoluteSize.Y / 2)
			SetPosition(Menu, NewPosition)
		end
	end)

	local MouseDownResize = false
	Resize.Activated:Connect(function()
		MouseDownResize = true
	end)

	UserInputService.InputEnded:Connect(function(Input)
		if Input.UserInputType == Enum.UserInputType.MouseButton1 then
			MouseDownResize = false
		end
	end)

	UserInputService.InputChanged:Connect(function(Input)
		if MouseDownResize and Input.UserInputType == Enum.UserInputType.MouseMovement then
			local MouseX = Input.Position.X
			local MouseY = Input.Position.Y
			
			local NewSizeX = math.clamp(MouseX - Menu.AbsolutePosition.X, 400, game.Players.LocalPlayer.PlayerGui.AbsoluteSize.X)
			local NewSizeY = math.clamp(MouseY - Menu.AbsolutePosition.Y, 300, game.Players.LocalPlayer.PlayerGui.AbsoluteSize.Y)
			
			redzlib.Save.UISize = {NewSizeX, NewSizeY}
			SetSize(Menu, UDim2.new(0, NewSizeX, 0, NewSizeY))
			SetSize(TabsHolder, UDim2.new(0, redzlib.Save.TabSize, 1, 0))
			SetSize(ContentHolder, UDim2.new(1, -redzlib.Save.TabSize, 1, -50))
		end
	end)

	local ToggleButton = Create("TextButton", Menu, {
		Size = UDim2.new(0, 30, 0, 30),
		Position = UDim2.new(1, -35, 0.5, 0),
		AnchorPoint = Vector2.new(1, 0.5),
		Text = "",
		BackgroundTransparency = 1
	})

	local CloseIcon = Create("ImageLabel", ToggleButton, {
		Size = UDim2.new(0, 15, 0, 15),
		Position = UDim2.new(0.5, 0, 0.5, 0),
		AnchorPoint = Vector2.new(0.5, 0.5),
		Image = redzlib.Icons["cross"],
		ImageColor3 = redzlib.Themes[redzlib.Save.Theme]["Color Text"],
		BackgroundTransparency = 1
	})

	ToggleButton.Activated:Connect(function()
		Menu.Visible = not Menu.Visible
	end)

	local InvitesHolder = Create("Frame", ScreenGui, {
		Size = UDim2.new(0, 180, 0, 0),
		Position = UDim2.new(0.5, -90, 0.5, 0),
		AnchorPoint = Vector2.new(0.5, 0.5),
		BackgroundTransparency = 1,
		AutomaticSize = "Y",
		LayoutOrder = 1
	})
	redzlib.Instances.InvitesHolder = InvitesHolder
	Make("List", InvitesHolder, UDim2.new(0, 0, 0, 10))

	return Menu, MakeTab, MakeSection, redzlib.Utility.MakeToggle, redzlib.Utility.MakeSlider, redzlib.Utility.MakeButton, redzlib.Utility.MakeOption, redzlib.Utility.MakeFlag, redzlib.Utility.MakeInvite, UpdateMenu
end

return redzlib
